---
title: "mbdm Tests"
author: "Philipp Hunziker"
date: "November 25, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set seed, load package

```{r dependencies}
set.seed(0)
library(spmle)
```


# Tests with Simulated Data

## Cross-sectional probit, no interdependence

```{r cs_probit}
## Set data parameters
G <- 1
N <- 10000
TT <- 1
K_outcome <- 1
has_temporal_lag = FALSE
has_spatial_lag = FALSE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = 0.5, beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```


## Cross-sectional spatial probit

```{r cs_spprobit}
## Set data parameters
G <- 1
N <- 10000
TT <- 1
K_outcome <- 1
has_temporal_lag = FALSE
has_spatial_lag = TRUE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = 0.5, beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```

## Panel spatial probit without temporal autoregression

```{r panel_tprobit}
## Set data parameters
G <- 1
N <- 1024
TT <- 10
K_outcome <- 1
has_temporal_lag = FALSE
has_spatial_lag = TRUE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = 0.5, beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```


## Panel spatio-temporal probit

```{r panel_sptprobit}
## Set data parameters
G <- 1
N <- 1024
TT <- 10
K_outcome <- 1
has_temporal_lag = TRUE
has_spatial_lag = TRUE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = 0.5, gamma = 0.25, beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```


## Multi-outcome cross-section with spatial-lag

```{r cs_moprobit}
## Set data parameters
G <- 2
N <- 1024
TT <- 1
K_outcome <- 1
has_temporal_lag = FALSE
has_spatial_lag = TRUE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = c(0.5, 0.5), lambda = c(0.25,0.25), beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```


## Multi-outcome panel with spatio-temporal lag (aka 'the full monty')

```{r cs_moprobitfull}
## Set data parameters
G <- 2
N <- 256
TT <- 10
K_outcome <- 1
has_temporal_lag = TRUE
has_spatial_lag = TRUE

## Make the data
data.ls <- simulate_data(G, N, TT, K_outcome, has_temporal_lag = has_temporal_lag, has_spatial_lag = has_spatial_lag,
                         rho = c(0.25, 0.25), lambda = c(0.25,0.25), gamma = 0.25, beta = rep(c(0,1), G))

## Make the mbdm object
mbdm <- MBDM$new(y_list = data.ls$y_list, X_list = data.ls$X_list, N = N, TT = TT,
                 W_t = data.ls$W_t, has_temporal_lag = has_temporal_lag)

## ML fit
theta_init <- runif(mbdm$n_parameters, min = -0.75, max = 0.75)
system.time(ml.fit <- mbdm$train(theta_init))

## Summary
summary(ml.fit)
```
