---
title: "spmle Examples"
author: "Philipp Hunziker"
date: "June 21, 2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Usage Examples

```{r package}
library(spmle)
```

## Cross-sectional Probit

```{r ex1}
## Set data parameters
N <- 1024
TT <- 1
K_outcome <- 1
beta <- c(-0.5, 1)
has_temporal_lag <- FALSE
has_spatial_lag <- FALSE
zero_period <- FALSE

## Make the data
data_ls <- simulate_data(N = N, TT = TT,
                         K_outcome = K_outcome,
                         beta = beta,
                         has_spatial_lag = has_spatial_lag,
                         has_temporal_lag = has_temporal_lag,
                         zero_period = zero_period)

## Make the model object
model <- STModel$new(y = data_ls$y, X = data_ls$X,
                     N = data_ls$N, TT = data_ls$TT,
                     W_t = data_ls$W_t,
                     has_temporal_lag = has_temporal_lag,
                     has_spatial_lag = has_spatial_lag,
                     zero_period = zero_period)

## ML fit
ml.fit <- model$autotrain()

## Summary
summary(ml.fit)
```

## Cross-sectional Spatial Probit

```{r ex2}
## Set data parameters
N <- 1024
TT <- 1
K_outcome <- 1
beta <- c(-0.5, 1)
rho <- 0.25
has_temporal_lag <- FALSE
has_spatial_lag <- TRUE
zero_period <- FALSE

## Make the data
data_ls <- simulate_data(N = N, TT = TT,
                         K_outcome = K_outcome,
                         beta = beta,
                         rho = rho,
                         has_spatial_lag = has_spatial_lag,
                         has_temporal_lag = has_temporal_lag,
                         zero_period = zero_period)

## Make the model object
model <- STModel$new(y = data_ls$y, X = data_ls$X,
                     N = data_ls$N, TT = data_ls$TT,
                     W_t = data_ls$W_t,
                     has_temporal_lag = has_temporal_lag,
                     has_spatial_lag = has_spatial_lag,
                     zero_period = zero_period)

## ML fit
ml.fit <- model$autotrain()

## Summary
summary(ml.fit)
```

## Temporal Autoregressive Probit

```{r ex3}
## Set data parameters
N <- 1024
TT <- 10
K_outcome <- 1
beta <- c(-0.5, 1)
gamma <- 0.25
has_temporal_lag <- TRUE
has_spatial_lag <- FALSE
zero_period <- TRUE

## Make the data
data_ls <- simulate_data(N = N, TT = TT,
                         K_outcome = K_outcome,
                         beta = beta, 
                         gamma = gamma,
                         has_spatial_lag = has_spatial_lag,
                         has_temporal_lag = has_temporal_lag,
                         zero_period = zero_period)

## Make the model object
model <- STModel$new(y = data_ls$y, X = data_ls$X,
                     N = data_ls$N, TT = data_ls$TT,
                     W_t = data_ls$W_t,
                     has_temporal_lag = has_temporal_lag,
                     has_spatial_lag = has_spatial_lag,
                     zero_period = zero_period)

## ML fit
ml.fit <- model$autotrain()

## Summary
summary(ml.fit)
```

## Spatiotemporal Probit

Note how here we trigger the Python speed-up by setting `use_py = TRUE` in the model instantiation.

```{r ex4}
## Set data parameters
N <- 1024
TT <- 10
K_outcome <- 1
beta <- c(-0.5, 1)
rho <- 0.25
gamma <- 0.25
has_temporal_lag <- TRUE
has_spatial_lag <- TRUE
zero_period <- TRUE

## Make the data
data_ls <- simulate_data(N = N, TT = TT,
                         K_outcome = K_outcome,
                         beta = beta, 
                         gamma = gamma,
                         rho = rho,
                         has_spatial_lag = has_spatial_lag,
                         has_temporal_lag = has_temporal_lag,
                         zero_period = zero_period)

## Make the model object
model <- STModel$new(y = data_ls$y, X = data_ls$X,
                     N = data_ls$N, TT = data_ls$TT,
                     W_t = data_ls$W_t,
                     has_temporal_lag = has_temporal_lag,
                     has_spatial_lag = has_spatial_lag,
                     zero_period = zero_period,
                     use_py = TRUE)  # use python speed-up!

## ML fit
ml.fit <- model$autotrain()

## Summary
summary(ml.fit)
```
